Update clone script for services to clone maintainer site too
IMGIITRoorkee/omniport-frontend pull request #33
Opened 2020-09-02 15:48 UTC by kmrinal19

2020-09-02 19:20 UTC, algomaster99 requested changes

2020-09-02 19:20 UTC, algomaster99 commented on scripts/clone/services.sh
> +clonerepo   "Apps"            "omniport-frontend-apps"            "apps"
@kmrinal19 you have mistakingly indented all the app names. Make sure you correct it.

2020-09-03 04:51 UTC, algomaster99 approved these changes
@kmrinal19 looks great!
@pradumangoyal have a look at it too

2020-09-03 05:44 UTC, pradumangoyal approved these changes

2020-09-03 09:19 UTC, merged